### ISSUE TITLE
Unable to pull image using latest tag

### ISSUE THREAD

**Issue by sweta96** [Robothy/local-s3#28]
https://hub.docker.com/r/luofuxiang/local-s3

The docker pull command given in the above link does not work

`docker pull luofuxiang/local-s3`
**Error:**
```
Using default tag: latest
Error response from daemon: manifest for luofuxiang/local-s3:latest not found: manifest unknown: manifest unknown
```

**Comment by Robothy** [comment]
The release workflow doesn't successfully push the Docker image with the `latest` tag to DockerHub. Created a [pull request](https://github.com/Robothy/local-s3/pull/30) to fix it.

**Comment by sweta96** [comment]
The latest tag is not pulling the latest image

**Comment by Robothy** [comment]
I checked that the latest image is pushed to DockerHub. Would you provide your docker command that pulling the latest image.
