### ISSUE TITLE
Implement put/get/delete object tagging API.

### ISSUE THREAD

**Issue by Robothy** [Robothy/local-s3#29]

**Comment by Robothy** [comment]
https://github.com/Robothy/local-s3/pull/32

**Comment by sweta96** [comment]
Has getObjectTagging, setObjectTagging been implemented and available in the latest image?

**Comment by Robothy** [comment]
They are implemented in the `master` branch but have not been released yet. They will be available in the image in the next release. About two weeks later.

If you want to try the latest feature immediately, you can build a snapshot image on your local machine.
```
cd local-s3/local-s3-docker
../gradlew dockerBuild
```
