### ISSUE TITLE
PutObjectRequest withMetadata() not implemented

### ISSUE THREAD

**Issue by andrewjackman** [Robothy/local-s3#58]
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/PutObjectRequest.html#withMetadata-com.amazonaws.services.s3.model.ObjectMetadata-

When I use the PutObjectRequest.builder().metadata(...) and retrieve the object, the metadata is empty.

**Comment by Robothy** [comment]
The `PutObjectRequest.builder().metadata(...)` method sets the [user-defined object metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata). Hope [this PR](https://github.com/Robothy/local-s3/pull/59) could resolve this issue.

**Comment by andrewjackman** [comment]
Fantastic - that seems to do what we need. Thanks for the fast turnaround. Once you have released a version containing that code, we can close this issue.
