### ISSUE TITLE
'GetBucketLocation' not supported

### ISSUE THREAD

**Issue by 6mo** [Robothy/local-s3#62]
local-s3 seems lightweight and easy to integrate.

When mocking a Minio S3 server, i get this error from Minio Client:

`Non-XML response from server. Response code: 501, Content-Type: null, body: <Error><Code>NotImplemented</Code><Message>LocalS3 doesn't support operation 'GetBucketLocation'. If you need this feature, please submit an issue at https://github.com/Robothy/local-s3/issues/new.</Message><RequestId/><ArgumentName/><ArgumentValue/><BucketName/><Key/><VersionId/></Error>`

**Comment by Robothy** [comment]
[GetBucketLocation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) will be supported soon. Maybe we can make the server return a fixed location `"local"` .

**Comment by Robothy** [comment]
Supported in version `1.11`.
