### ISSUE TITLE
Is there a workaround for method createBucket

### ISSUE THREAD

**Issue by andresmargalef** [Robothy/local-s3#79]
With the last version 1.12.2, using the example on readme
```java
@LocalS3(port = 9090)
class AppTest {
    @Test
    void test(AmazonS3 s3) {
        s3.createBucket("my-bucket");
    }
}
```
the method fail trying to create an object. I think there is a bug because aws sdk always includes the last slash [here](https://github.com/aws/aws-sdk-java/blob/c5275d717c9265e97ddb1eee71d8f930a7d41112/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/S3RequestEndpointResolver.java#L141) but the router factory [here](https://github.com/Robothy/local-s3/blob/9e2ae02ad4d6d330e27db13aa8852656a28904fc/local-s3-rest/src/main/java/com/robothy/s3/rest/handler/LocalS3RouterFactory.java#L46) creates a route without slash, so this route never matches.

**Comment by andresmargalef** [comment]
In master seems to be fixed [here](https://github.com/Robothy/local-s3/pull/78/files#diff-5a9c1d84bef468bf3f617252617c9ad0373ebeaea163cf5cedfee003a8632a6aR74).

When will a release be created?

.. and thanks for this  library, it is really useful

**Comment by Robothy** [comment]
@andresmargalef `1.13` is published. The new version should fix this issue.
