### ISSUE TITLE
Any plans to get rid of AWS SDK v1?

### ISSUE THREAD

**Issue by christopher-cudennec** [Robothy/local-s3#80]
Hi @Robothy !

First of all, thanks for your great library! We've recently used it to replace the unmaintained [findify/s3mock](https://github.com/findify/s3mock) in our open source libraries [sda-dropwizard-commons](https://github.com/SDA-SE/sda-dropwizard-commons/blob/PLP-820-sda-dropwizard-commons-update-to-dropwizard-4/docs/migration-guides/MIGRATION_GUIDE_v5_to_v6.md#8-sda-commons-server-s3) and [sda-spring-boot-commons](https://github.com/SDA-SE/sda-spring-boot-commons/pull/540).

During the update process of both libraries we switched from AWS SDK v1 to v2. Originally, I wanted to exclude v1 completely, but I've noticed that you're still using v1 to create a new `AmazonS3` client [in your JUnit 5 extension](https://github.com/Robothy/local-s3/blob/master/local-s3-jupiter/src/main/java/com/robothy/s3/jupiter/extensions/AmazonS3Resolver.java). Do you have any plans to migrate to v2 of the API completely? For me, that feels cleaner because you're actually using both versions of the AWS SDK in your [build.gradle](https://github.com/Robothy/local-s3/blob/master/local-s3-jupiter/build.gradle#L8). It would also simplify dependency management for us if we can rely on v2 of the AWS SDK.

Cheers,

Christopher

**Comment by Robothy** [comment]
That's an interesting point. I plan to eliminate both dependencies from the LocalS3 library, empowering users to choose which one or both to include in their test classpath. If AWS SDK v1 is included, LocalS3 will facilitate the instantiation of `AmazonS3` instances. With AWS SDK v2 added, LocalS3 will seamlessly support the creation of S3Client. Moreover, if both are added to the classpath, LocalS3 will cater to both scenarios.

For your specific situation, by simply adding AWS SDK v2 into your classpath, LocalS3 will abstain from introducing AWS SDK v1 dependencies.

This change will be available soon.

**Comment by christopher-cudennec** [comment]
That sounds like the perfect solution for users of your library! Thanks for the quick answer! 👍 
I will close the ticket. 🌻
