### ISSUE TITLE
Provide before and after methods to JUnit 5 extension?

### ISSUE THREAD

**Issue by christopher-cudennec** [Robothy/local-s3#81]
Hi @Robothy !

Thanks again for providing your great library! 😃 

I'm opening a second issue to have separate discussions for different topics 😃 

One thing that bothered me, when migrating to your library was the fact that I can't use your extension in the `beforeEach` or `afterEach` methods. Would you be interested in taking over something like our [custom extension](https://github.com/SDA-SE/sda-dropwizard-commons/blob/PLP-820-sda-dropwizard-commons-update-to-dropwizard-4/sda-commons-server-s3-testing/src/main/java/org/sdase/commons/server/s3/testing/S3ClassExtension.java)?

As you can see in the [test](https://github.com/SDA-SE/sda-dropwizard-commons/blob/PLP-820-sda-dropwizard-commons-update-to-dropwizard-4/sda-commons-server-s3-testing/src/test/java/org/sdase/commons/server/s3/testing/S3ClassExtensionTest.java#L27), you can use the extension in the `beforeEach` method to clean all objects.

Furthermore I find it quite convenient to define the S3 client as a field that can be used in all my methods instead of repeating the AmazonS3 as method parameter in all my test methods.

Of course, it's your code - if it does not suite your style or taste, we can also live with maintaining the class on our side.

Thanks and cheers,

Christopher

**Comment by Robothy** [comment]
@christopher-cudennec  Perhaps LocalS3 could facilitate the injection of S3 client instances into both static and non-static fields within a test class. This would enable us to utilize it in the following manner:
```java
class TestApp {

    @LocalS3
    S3Client client;

    @AfterEach
    void cleanup() {}
    
    @Test
    void test() {
        client.putObject(....)
    }
}
```

**Comment by christopher-cudennec** [comment]
Yes, that would give us the flexibility we're looking for! 👏 

Same goes for the S3 endpoint which we want to re-use in our application as configuration parameters. We usually solve that by ordering the Junit 5 extensions (using `@Order` + `@RegisterExtension`) and asking for the actual s3 endpoint. This [example](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-server-s3/src/test/java/org/sdase/commons/server/s3/S3BundleTest.java#L25) should illustrate what I mean:

```
  @RegisterExtension
  @Order(0)
  static final S3ClassExtension S3 =
      S3ClassExtension.builder().putObject("bucket", "key", "data").build();

  @RegisterExtension
  @Order(1)
  static final DropwizardAppExtension<Config> DW =
      new DropwizardAppExtension<>(
          TestApp.class,
          null,
          randomPorts(),
          config("s3Config.endpoint", S3::getEndpoint),
          config("s3Config.accessKey", "access-key"),
          config("s3Config.secretKey", "secret-key"));
```

But maybe that should be worth a separate issue. 😃

**Comment by Robothy** [comment]
Hi @christopher-cudennec ,

The `local-s3-rest` appears to be a better fit for your situation compared to `local-s3-jupiter`. To implement this, you can declare a static field in LocalS3 type within your test class and initialize the S3Client in a static block. Subsequently, you can employ the client within the JUnit 5 lifecycle method, passing the endpoint to your custom extensions. Here's an example:

````java
public class AppTest{


  static LocalS3 localS3 = LocalS3.builder().build();

  static String s3Endpoint;

  static S3Client client;

  static {
    localS3.start();
    s3Endpoint  = "http://localhost:" + localS3.getPort();
    client = S3Client.builder()
      .endpointOverride(URI.create(s3Endpoint))
      .credentialsProvider(AnonymousCredentialsProvider.create())
      .forcePathStyle(true)
      .region(Region.of("local"))
      .build();
  }

  @RegisterExtension
  CustomExtension customExtension = new CustomExtension(s3Endpoint);


  @BeforeEach
  void beforeEach() {
    client.createBucket(b -> b.bucket("my-bucket"));
  }

  @Test
  void test() {
    client.headBucket(b -> b.bucket("my-bucket"));
  }

  @AfterAll
  static void afterAll() {
    localS3.shutdown();
  }

}
```

**Comment by christopher-cudennec** [comment]
Hi @Robothy !

I guess defining it in a static block is almost the same like wrapping it in a custom JUnit extension which is better for reuse. And the result will be pretty close to our own extension that we've [already created](https://github.com/SDA-SE/sda-dropwizard-commons/blob/PLP-820-sda-dropwizard-commons-update-to-dropwizard-4/sda-commons-server-s3-testing/src/main/java/org/sdase/commons/server/s3/testing/S3ClassExtension.java).

Thanks a lot for your comments and recommendations! 🌻 I will close this issue because we can solve it on our own. If you think you've found something that you can take over to the library, feel free to do so!

Keep up the great work! 🚀 

Cheers,

Christopher
